/**
 * icons.ts — single entry point for semantic icons.
 *
 * Rules (enforced by scripts/check-ui-debt.mjs):
 *   1. Semantic UI icons come from lucide-react, re-exported here.
 *      New components must import from "../lib/icons" (or "../../lib/icons"),
 *      not directly from "lucide-react".
 *   2. Brand/product logos (model providers, file types, third-party brands)
 *      use @lobehub/icons or @iconify/react — never lucide, never custom SVG.
 *   3. No emoji or glyph characters as icons in components. The only
 *      exception is AgentAvatar, the per-agent identity art system.
 *   4. Default size 14–16px, strokeWidth 1.75 (mc-icon-button rules).
 *
 * The list below is exactly the set already in use across src.v2 — add new
 * lucide icons here first, then import from this module.
 */
export {
  AlertCircle,
  ArrowDown,
  ArrowLeft,
  ArrowRight,
  ArrowUp,
  AtSign,
  Blend,
  Bot,
  Braces,
  Bug,
  CalendarClock,
  Check,
  CheckCircle,
  CheckCircle2,
  ChevronDown,
  ChevronRight,
  ChevronUp,
  Circle,
  CircleAlert,
  CircleDot,
  CircleSlash2,
  ClipboardCopy,
  Clock,
  Clock3,
  Code2,
  Columns2,
  Command,
  Copy,
  CornerDownLeft,
  Database,
  Download,
  Edit3,
  ExternalLink,
  Eye,
  EyeOff,
  FileCheck2,
  FileCode2,
  FileDiff,
  FileDown,
  FileSearch,
  FileText,
  FileType,
  FileWarning,
  Files,
  Folder,
  FolderOpen,
  Gauge,
  GitBranch,
  GitCompare,
  Globe,
  Globe2,
  Hammer,
  History,
  Image,
  Image as ImageIcon,
  Info,
  KeyRound,
  Layers,
  Lightbulb,
  Link,
  ListChecks,
  LoaderCircle,
  LockKeyhole,
  Maximize2,
  MessageCircle,
  MessageSquare,
  MessageSquareText,
  MessagesSquare,
  Minimize2,
  Minus,
  Monitor,
  MonitorPlay,
  Moon,
  MoreHorizontal,
  OctagonAlert,
  Paperclip,
  Pause,
  Pencil,
  Play,
  Plus,
  Quote,
  RefreshCcw,
  RefreshCw,
  RotateCcw,
  RotateCw,
  Rows3,
  Save,
  Search,
  SearchCode,
  Send,
  Settings,
  ShieldAlert,
  ShieldCheck,
  Sparkles,
  Square,
  SquarePen,
  SquareTerminal,
  Sun,
  Target,
  TerminalSquare,
  Trash2,
  TrendingUp,
  TriangleAlert,
  Upload,
  Wrench,
  X,
  XCircle,
} from "lucide-react";
